### PR TITLE
Remove facebook_id requirement for auth

### PR DESCRIPTION
**Pull request by synical**

### CODE REVIEW

**Comment by charliewolf** [comment]
why?

**Comment by Jackojc** [comment]
Pretty sure the facebook ID is mandatory.

**Comment by synical** [comment]
Nope, as of the new facebook oauth changes last month, facebook_id is no longer a requirement. Test it out, you can till auth.

**Comment by Jackojc** [comment]
Oh, Interesting. Maybe it would be best to, Instead of removing the ID, Make it a kwarg so that it can be optional. It could be good for have a store of profiles you want to use for Pynder when you want to check which profile is which.

**Comment by synical** [comment]
So you mean pass in the facebook_id to change which FB account you are authing with?

**Comment by charliewolf** [comment]
@Jackojc that doesn't make sense to me. the token is still tied to a given ID so passing it anyway wouldn't really provide any benefit

**Comment by synical** [comment]
Yeah the token is the only source for auth now so I don't think the ID does anything.

**Comment by Jackojc** [comment]
Yeah I guess so, Is there anywhere I can read more about the recent facebook API changes, synical?

**Comment by synical** [comment]
Found out that the token method wasn't working anymore and the saw this:

https://gist.github.com/rtt/10403467#gistcomment-1846343

Seems someone else has done this too:

https://github.com/tarraschk/TinderAutoLike/commit/c76e7fb7ed334506137db73169c0a3305196d128

**Pull request merged**
