### PR TITLE
Improvements & Fixes 2

### PR DESCRIPTION
**Pull request by GreatOldOne**
Improvements:
-You can now upload photos through the Profile.add_photo() method.
-You can now delete photos through the Profile.delete_photo() method.
-Added a RecsTimeout exception to prevent useless loops.

Fixes:
-Upon some analysis of Tinder's API distance data, it became clear that
Tinder Online (Web version) was glitched and reporting miles as
kilometers. Properly fixed this, returning -1 if no distance could be
determined.

### CODE REVIEW

**Comment by GreatOldOne** [comment]
I hate those checks...

Anyway it's here, and closed the former PR.

**Comment by GreatOldOne** [comment]
I've a fix for KeyError: 'bio' when the profile has no bio yet too, but waiting for this to be merged.

**Comment by charliewolf** [comment]
Thanks. Will review by the end f the weekend.

**Comment by charliewolf** [comment]
Can you submit photo stuff separately? I'm not sure I like the way you're handling the `base` constants. I'm thinking we should do something like use the `API_BASE` by default unless the `path` starts with `^https?://`

**Comment by GreatOldOne** [comment]
API_BASE is https too.

**Comment by GreatOldOne** [comment]
Both of them are.

**Comment by GreatOldOne** [comment]
This was the way I found without overly changing too much code.

**Comment by GreatOldOne** [comment]
In any case, if you still don't like it, just let me know how you would like me to write it and I'll submit another commit.

**Comment by charliewolf** [comment]
@GreatOldOne Sorry, I didn't phrase that in the most clear way. Take a look at my `full-url-support` branch that I just pushed, merge that into yours. Then just do `CONTENT_BASE + "/media"` as the second argument for `_request` in `add_profile_photo`. Let me know if that still doesn't make sense.

**Comment by GreatOldOne** [comment]
@charliewolf How about the same method but using a method instead of inline?

self._full_url(url)

`def _full_url(url):
    if url.startswith("http://") or url.startswith("https://"):
        return url
    else:
        return constants.BASE_API + url`

**Comment by charliewolf** [comment]
:thumbsup: sounds good to me

**Comment by GreatOldOne** [comment]
Refactored and pushed.

**Pull request merged**
