### PR TITLE
Improvements & Fixes 3

### PR DESCRIPTION
**Pull request by GreatOldOne**
Improvements:
-Added 'birth_date' as an attribute for Profile.
-Added 'age' as a property for Profile.
-Profile.discoverable is now updatable (newly created profiles have
discoverable set at false).
-User.report() and TinderAPI.report() can now take a text parameter for
cause 0 (Other).
-Added Match.report() since once matched, the Tinder API will only take
the match ID for reports.
-Added report cause constants as class variables to User
(User.REPORT_*).

Fixes:
-Fixed updatable Profile attributes not yet available raising KeyError
exceptions. Now they properly return None.

### CODE REVIEW

**Comment by charliewolf** [comment]
I think the report causes should probably become an `Enum`

**Comment by GreatOldOne** [comment]
@charliewolf Enum is Python3, though.

Unless you want me to write:

`class ReportEnum(object) ...`

**Comment by charliewolf** [comment]
@GreatOldOne we can include `enum34` as a required dependency for python versions that don't support `Enum`

**Comment by GreatOldOne** [comment]
Your call. Just let me know how you want me to write it and I'll push it.

**Comment by charliewolf** [comment]
````class ReportCause(Enum):
    Spam = 1
    ...
```

**Comment by GreatOldOne** [comment]
Pushed as requested.

**Review by charliewolf — APPROVED** [review]

**Comment by charliewolf** [comment]
really awesome work @GreatOldOne. Thanks so much for these improvements!

**Pull request merged**
